@startuml erd
hide empty members
hide circle
skinparam classAttributeIconSize 0

skinparam Padding 8
skinparam Linetype ortho

class User {}
class Role{}
class Suggestion{}
class Gathering{}
class UserSuggestion{}
class UserGathering{}

Role --o{ User
User --o{ UserGathering
Gathering --o{ UserGathering
User --o{ UserSuggestion
Suggestion --o{ UserSuggestion


@enduml
